-- Health Office Data Tables
-- Component ID: 305
-- Run against postgres-data / dashboard.

BEGIN;

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;

CREATE TABLE IF NOT EXISTS public.food_safety_health_office_tpe (
    ogc_fid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_time text,
    source_row_no integer,
    name text,
    city text,
    district text,
    district_code text,
    agency_type text,
    address text,
    phone text,
    website text,
    source_dataset text,
    source_url text,
    geocoding_address text,
    location_method text,
    lng double precision,
    lat double precision,
    wkb_geometry public.geometry(Point, 4326)
);

CREATE TABLE IF NOT EXISTS public.food_safety_health_office_ntpe (
    ogc_fid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_time text,
    source_row_no integer,
    office_id text,
    name text,
    city text,
    district text,
    agency_type text,
    address text,
    phone text,
    extension text,
    zipcode text,
    open_time text,
    website text,
    source_dataset text,
    source_url text,
    geocoding_address text,
    location_method text,
    lng double precision,
    lat double precision,
    wkb_geometry public.geometry(Point, 4326)
);

COMMIT;
