BEGIN;

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;

CREATE TABLE IF NOT EXISTS public.food_safety_market_tpe (
    ogc_fid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_time text,
    market_id text,
    city text,
    district text,
    name text,
    type text,
    address text,
    stall_total integer,
    vegetable_stalls integer,
    fruit_stalls integer,
    meat_stalls integer,
    seafood_stalls integer,
    poultry_stalls integer,
    grain_stalls integer,
    flower_stalls integer,
    grocery_stalls integer,
    general_merchandise_stalls integer,
    food_stalls integer,
    other_stalls integer,
    lng double precision,
    lat double precision,
    wkb_geometry public.geometry(Point, 4326)
);

CREATE TABLE IF NOT EXISTS public.food_safety_market_ntpe (
    ogc_fid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_time text,
    market_id text,
    name text,
    city text,
    city_code text,
    district text,
    district_code text,
    address text,
    phone text,
    type text,
    stall_total double precision,
    produce_stalls double precision,
    meat_stalls double precision,
    seafood_stalls double precision,
    poultry_stalls double precision,
    grain_stalls double precision,
    grocery_stalls double precision,
    flower_stalls double precision,
    food_stalls double precision,
    general_merchandise_stalls double precision,
    other_stalls double precision,
    vacant_stalls double precision,
    lng double precision,
    lat double precision,
    wkb_geometry public.geometry(Point, 4326)
);

COMMIT;
