BEGIN;

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;

CREATE TABLE IF NOT EXISTS public.food_safety_logistics_vendor (
    ogc_fid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_time text,
    city text,
    normalized_city text,
    district text,
    vendor_category_code text,
    vendor_category text,
    source_row_no integer,
    source_city_row_no integer,
    registration_item text,
    registration_no text,
    name text,
    address text,
    geocoding_address text,
    company_registration_name text,
    source_page integer,
    point_type text,
    location_method text,
    osm_query text,
    osm_display_name text,
    taipei_house_key text,
    lng double precision,
    lat double precision,
    wkb_geometry public.geometry(Point, 4326)
);

COMMIT;
