-- Water Quality Data Tables
-- Component ID: 306
-- Run against postgres-data / dashboard.

BEGIN;

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;

CREATE TABLE IF NOT EXISTS public.water_quality_tpe (
    ogc_fid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    etl_update_time timestamp without time zone,
    source_row_no integer,
    name text,
    english_name text,
    city text,
    district text,
    address text,
    water_sources text,
    data_time text,
    qualified text,
    ph double precision,
    turbidity_ntu double precision,
    free_residual_chlorine_mg_l double precision,
    total_hardness_mg_l double precision,
    total_dissolved_solids_mg_l double precision,
    coliform_cfu_100ml text,
    source_dataset text,
    source_url text,
    location_method text,
    lng double precision,
    lat double precision,
    wkb_geometry public.geometry(Point, 4326)
);

CREATE TABLE IF NOT EXISTS public.water_quality_ntpe (
    ogc_fid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    etl_update_time timestamp without time zone,
    source_row_no integer,
    name text,
    english_name text,
    city text,
    district text,
    address text,
    water_sources text,
    data_time text,
    qualified text,
    ph double precision,
    turbidity_ntu double precision,
    free_residual_chlorine_mg_l double precision,
    total_hardness_mg_l double precision,
    total_dissolved_solids_mg_l double precision,
    coliform_cfu_100ml text,
    source_dataset text,
    source_url text,
    location_method text,
    lng double precision,
    lat double precision,
    wkb_geometry public.geometry(Point, 4326)
);

WITH seed (
    etl_update_time, source_row_no, name, english_name, city, district, address,
    water_sources, data_time, qualified, ph, turbidity_ntu,
    free_residual_chlorine_mg_l, total_hardness_mg_l,
    total_dissolved_solids_mg_l, coliform_cfu_100ml, source_dataset,
    source_url, location_method, lng, lat
) AS (
    VALUES
        ('2026-05-02 00:00:00'::timestamp, 1, '直潭淨水場', '', '臺北市', '新店區', '', '新店溪', '114年度', '年度均值', 7.3, 0.1, 0.54, 54.9, 93.1, '<1', '臺北自來水水質檢驗(淨水場清水水質)', 'https://data.taipei/dataset/detail?id=9626c65d-8fe7-45bb-bbe2-7439bed81010', '固定淨水場座標', 121.5310, 24.9520),
        ('2026-05-02 00:00:00'::timestamp, 2, '長興淨水場', '', '臺北市', '文山區', '', '新店溪', '114年度', '年度均值', 7.4, 0.2, 0.56, 55.5, 94.0, '<1', '臺北自來水水質檢驗(淨水場清水水質)', 'https://data.taipei/dataset/detail?id=9626c65d-8fe7-45bb-bbe2-7439bed81010', '固定淨水場座標', 121.5460, 25.0150),
        ('2026-05-02 00:00:00'::timestamp, 3, '公館淨水場', '', '臺北市', '中正區', '', '新店溪', '114年度', '年度均值', 7.3, 0.1, 0.55, 55.0, 93.8, '<1', '臺北自來水水質檢驗(淨水場清水水質)', 'https://data.taipei/dataset/detail?id=9626c65d-8fe7-45bb-bbe2-7439bed81010', '固定淨水場座標', 121.5320, 25.0140),
        ('2026-05-02 00:00:00'::timestamp, 4, '雙溪淨水場', '', '臺北市', '士林區', '', '雙溪', '114年度', '年度均值', 7.4, 0.48, 0.52, 44.0, 84.0, '<1', '臺北自來水水質檢驗(淨水場清水水質)', 'https://data.taipei/dataset/detail?id=9626c65d-8fe7-45bb-bbe2-7439bed81010', '固定淨水場座標', 121.5720, 25.1010),
        ('2026-05-02 00:00:00'::timestamp, 5, '陽明淨水場', '', '臺北市', '北投區', '', '陽明山區水源', '114年度', '年度均值', 7.5, 0.32, 0.53, 42.0, 82.0, '<1', '臺北自來水水質檢驗(淨水場清水水質)', 'https://data.taipei/dataset/detail?id=9626c65d-8fe7-45bb-bbe2-7439bed81010', '固定淨水場座標', 121.5440, 25.1540)
)
INSERT INTO public.water_quality_tpe (
    etl_update_time, source_row_no, name, english_name, city, district, address,
    water_sources, data_time, qualified, ph, turbidity_ntu,
    free_residual_chlorine_mg_l, total_hardness_mg_l,
    total_dissolved_solids_mg_l, coliform_cfu_100ml, source_dataset,
    source_url, location_method, lng, lat, wkb_geometry
)
SELECT
    etl_update_time, source_row_no, name, english_name, city, district, address,
    water_sources, data_time, qualified, ph, turbidity_ntu,
    free_residual_chlorine_mg_l, total_hardness_mg_l,
    total_dissolved_solids_mg_l, coliform_cfu_100ml, source_dataset,
    source_url, location_method, lng, lat, ST_SetSRID(ST_MakePoint(lng, lat), 4326)
FROM seed
WHERE NOT EXISTS (SELECT 1 FROM public.water_quality_tpe);

WITH seed (
    etl_update_time, source_row_no, name, english_name, city, district, address,
    water_sources, data_time, qualified, ph, turbidity_ntu,
    free_residual_chlorine_mg_l, total_hardness_mg_l,
    total_dissolved_solids_mg_l, coliform_cfu_100ml, source_dataset,
    source_url, location_method, lng, lat
) AS (
    VALUES
        ('2026-05-02 00:00:00'::timestamp, 1, '貢寮淨水場', 'Gongliao', '新北市', '貢寮區', '新北市貢寮區下雙溪街20號', '', '2026/04/24', 'Y', 7.3, 0.4, 0.7, 25.1, 75.0, '<1', '臺灣自來水公司平均水質', 'https://www.water.gov.tw/ch/WaterQuality/Detail/1991?nodeId=4631', '固定淨水場座標', 121.9206, 25.0199),
        ('2026-05-02 00:00:00'::timestamp, 2, '老梅淨水場', 'Laomei', '新北市', '石門區', '新北市石門區老梅里七股33之2號', '', '2026/04/24', 'Y', 7.7, 0.45, 0.56, 24.4, 66.6, '<1', '臺灣自來水公司平均水質', 'https://www.water.gov.tw/ch/WaterQuality/Detail/1990?nodeId=4631', '固定淨水場座標', 121.5497, 25.2921),
        ('2026-05-02 00:00:00'::timestamp, 3, '林莊淨水場', 'Linjhuang', '新北市', '金山區', '新北市金山區重合里林口28-2號', '', '2026/04/24', 'Y', 7.8, 0.55, 0.71, 29.4, 76.2, '<1', '臺灣自來水公司平均水質', 'https://www.water.gov.tw/ch/WaterQuality/Detail/1989?nodeId=4631', '固定淨水場座標', 121.6125, 25.2236),
        ('2026-05-02 00:00:00'::timestamp, 4, '坪林淨水場', 'Pinglin', '新北市', '坪林區', '新北市坪林區坪林里國中路3號', '', '2026/04/24', 'Y', 7.6, 0.25, 0.64, 23.6, 65.2, '<1', '臺灣自來水公司平均水質', 'https://www.water.gov.tw/ch/WaterQuality/Detail/1988?nodeId=4631', '固定淨水場座標', 121.7118, 24.9365),
        ('2026-05-02 00:00:00'::timestamp, 5, '員山淨水場', 'Yuanshan', '新北市', '瑞芳區', '新北市瑞芳區員山路19-1號', '', '2026/04/24', 'Y', 7.7, 0.5, 0.63, 31.6, 91.0, '<1', '臺灣自來水公司平均水質', 'https://www.water.gov.tw/ch/WaterQuality/Detail/1987?nodeId=4631', '固定淨水場座標', 121.8076, 25.1055),
        ('2026-05-02 00:00:00'::timestamp, 6, '板新淨水場', 'Bansin', '新北市', '三峽區', '新北市三峽區復興路551號', '', '2026/04/24', 'Y', 7.3, 0.2, 0.7, 69.7, 127.0, '<1', '臺灣自來水公司平均水質', 'https://www.water.gov.tw/ch/WaterQuality/Detail/1986?nodeId=4631', '固定淨水場座標', 121.3766, 24.9389)
)
INSERT INTO public.water_quality_ntpe (
    etl_update_time, source_row_no, name, english_name, city, district, address,
    water_sources, data_time, qualified, ph, turbidity_ntu,
    free_residual_chlorine_mg_l, total_hardness_mg_l,
    total_dissolved_solids_mg_l, coliform_cfu_100ml, source_dataset,
    source_url, location_method, lng, lat, wkb_geometry
)
SELECT
    etl_update_time, source_row_no, name, english_name, city, district, address,
    water_sources, data_time, qualified, ph, turbidity_ntu,
    free_residual_chlorine_mg_l, total_hardness_mg_l,
    total_dissolved_solids_mg_l, coliform_cfu_100ml, source_dataset,
    source_url, location_method, lng, lat, ST_SetSRID(ST_MakePoint(lng, lat), 4326)
FROM seed
WHERE NOT EXISTS (SELECT 1 FROM public.water_quality_ntpe);

COMMIT;
