--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4
-- Dumped by pg_dump version 16.8 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;



--
-- Data for Name: component_charts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.component_charts (index, color, types, unit) FROM stdin;
youbike_availability	{#9DC56E,#356340,#9DC56E}	{GuageChart,BarPercentChart}	輛
ebus_percent	{#9DC56E,#356340,#9DC56E}	{IconPercentChart,BarPercentChart}	輛
city_age_distribution	{#24B0DD,#56B96D,#F8CF58,#F5AD4A,#E170A6,#ED6A45,#AF4137,#10294A}	{DistrictChart,ColumnChart}	仟人
dependency_aging	{#67baca,#fbf3ac}	{ColumnLineChart,TimelineSeparateChart}	%
aging_kpi	{#F65658,#F49F36,#F5C860,#9AC17C,#4CB495,#569C9A,#60819C,#2F8AB1}	{TextUnitChart}	\N
aging_workforce_trend	{#24B0DD,#56B96D,#F8CF58,#F5AD4A,#E170A6,#ED6A45,#AF4137,#10294A}	{BarPercentChart,RadarChart,ColumnChart}	%
bike_network	{#a0b8e8,#b7ff98}	{DonutChart,BarChart}	公里
bike_map	{#a0b8e8,#b7ff98}	{MapLegend}	條
fda_good_restaurants	{#8FD9A8,#F6D982}	{DistrictChart,RankListChart,TreemapChart}	家
food_source	{#30B68F,#F5B041,#4A90E2,#D84C73,#8E63C7,#F2C94C,#7A8793,#2F7D6D,#C2573E,#1E88E5,#00A6A6,#AF4137}	{DistrictChart,TreemapChart,BarChart}	處
food_safety_market	{#30B68F,#F5B041,#4A90E2,#D84C73,#8E63C7,#F2C94C,#7A8793,#C6A15B}	{DonutChart,TreemapChart,BarChart}	攤
food_safety_logistics_vendor	{#4A90E2,#D84C73,#30B68F,#F5B041,#8E63C7,#F2C94C,#7A8793,#2F7D6D,#C2573E,#1E88E5,#00A6A6,#AF4137}	{DistrictChart,TreemapChart,BarChart}	家
food_safety_health_office	{#2F7D6D,#C2573E,#F2C94C}	{DonutChart,TreemapChart,BarChart}	處
water_quality	{#2F7D6D,#30B68F,#1E88E5,#F5B041,#D84C73}	{BarChart}	NTU
cdc_infectious_disease	{#4CB495,#F5C860,#ED6A45,#4A90E2}	{ColumnLineChart}	人次
food_safety_death_share	{#D84C73,#F5B041,#4A90E2,#8E63C7}	{TimelineSeparateChart}	%
food_processing_pass_rate	{#4CB495,#F5C860,#ED6A45,#1E88E5,#8E63C7}	{TimelineSeparateChart}	%
\.


--
-- Data for Name: component_maps; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.component_maps (id, index, title, type, source, size, icon, paint, property) FROM stdin;
70	youbike_realtime	youbike站點	symbol	geojson	\N	youbike	{}	[{"key":"sna","name":"場站名稱"},{"key":"sno","name":"場站ID"},{"key":"available_return_bikes","name":"可還車位"},{"key":"available_rent_general_bikes","name":"剩餘車輛"}]
99	youbike_realtime_metrotaipei	youbike站點	symbol	geojson	\N	youbike	{}	[{"key":"sna","name":"場站名稱"},{"key":"sno","name":"場站ID"},{"key":"available_return_bikes","name":"可還車位"},{"key":"available_rent_general_bikes","name":"剩餘車輛"}]
100	bike_network_tpe	自行車路網	line	geojson	\N	\N	{"line-color":["match",["get","direction"],"雙向","#097138","單向","#007BFF","#808080"]}	[\r\n  {"key": "data_time", "name": "數據時間"},\r\n  {"key": "route_name", "name": "路線名稱"},\r\n  {"key": "city_code", "name": "城市代碼"},\r\n  {"key": "city", "name": "城市"},\r\n  {"key": "road_section_start", "name": "起點路段"},\r\n  {"key": "road_section_end", "name": "終點路段"},\r\n  {"key": "direction", "name": "方向"},\r\n  {"key": "cycling_length", "name": "自行車道長度"},\r\n  {"key": "finished_time", "name": "完工時間"},\r\n  {"key": "update_time", "name": "更新時間"}\r\n]
101	bike_network_metrotaipei	自行車路網	line	geojson	\N	\N	{"line-color":["match",["get","direction"],"雙向","#097138","單向","#007BFF","#808080"]}	[\r\n  {"key": "data_time", "name": "數據時間"},\r\n  {"key": "route_name", "name": "路線名稱"},\r\n  {"key": "city_code", "name": "城市代碼"},\r\n  {"key": "city", "name": "城市"},\r\n  {"key": "road_section_start", "name": "起點路段"},\r\n  {"key": "road_section_end", "name": "終點路段"},\r\n  {"key": "direction", "name": "方向"},\r\n  {"key": "cycling_length", "name": "自行車道長度"},\r\n  {"key": "finished_time", "name": "完工時間"},\r\n  {"key": "update_time", "name": "更新時間"}\r\n]
201	food_safety_market_tpe	臺北市公有市場	circle	geojson	big	\N	{"circle-color":"#30B68F","circle-radius":["interpolate",["linear"],["coalesce",["to-number",["get","stall_total"]],1],0,4,50,6,150,9,300,13,500,17],"circle-opacity":0.72,"circle-stroke-color":"#F7FFF9","circle-stroke-width":1}	[{"key":"name","name":"市場名稱"},{"key":"district","name":"行政區"},{"key":"stall_total","name":"總攤位數"},{"key":"vegetable_stalls","name":"蔬菜攤位"},{"key":"fruit_stalls","name":"青果攤位"},{"key":"meat_stalls","name":"獸肉攤位"},{"key":"seafood_stalls","name":"漁產攤位"},{"key":"poultry_stalls","name":"家禽攤位"},{"key":"grain_stalls","name":"糧食攤位"},{"key":"flower_stalls","name":"花卉攤位"},{"key":"grocery_stalls","name":"雜貨攤位"},{"key":"general_merchandise_stalls","name":"百貨攤位"},{"key":"food_stalls","name":"飲食攤位"},{"key":"other_stalls","name":"其他攤位"}]
202	food_safety_market_ntpe	新北市公有市場	circle	geojson	big	\N	{"circle-color":"#F5B041","circle-radius":["interpolate",["linear"],["coalesce",["to-number",["get","stall_total"]],80],0,4,50,6,150,9,300,13,500,17],"circle-opacity":0.72,"circle-stroke-color":"#FFF8E8","circle-stroke-width":1}	[{"key":"name","name":"市場名稱"},{"key":"district","name":"行政區"},{"key":"stall_total","name":"總攤位數"},{"key":"produce_stalls","name":"果菜攤位"},{"key":"meat_stalls","name":"畜肉攤位"},{"key":"seafood_stalls","name":"魚蝦攤位"},{"key":"poultry_stalls","name":"禽肉攤位"},{"key":"grain_stalls","name":"糧食攤位"},{"key":"grocery_stalls","name":"雜貨攤位"},{"key":"flower_stalls","name":"花卉攤位"},{"key":"food_stalls","name":"飲食攤位"},{"key":"general_merchandise_stalls","name":"百貨攤位"},{"key":"other_stalls","name":"其他攤位"},{"key":"vacant_stalls","name":"空攤"},{"key":"address","name":"地址"},{"key":"phone","name":"電話"},{"key":"type","name":"市場型態"}]
203	food_safety_logistics_vendor_tpe	臺北市食品物流業者	circle	geojson	big	\N	{"circle-color":"#4A90E2","circle-radius":["interpolate",["linear"],["zoom"],9,3,12,5,15,8],"circle-opacity":0.72,"circle-stroke-color":"#F3F8FF","circle-stroke-width":1}	[{"key":"name","name":"業者名稱"},{"key":"registration_no","name":"食品業者登錄字號"},{"key":"company_registration_name","name":"公司/商業登記名稱"},{"key":"city","name":"縣市"},{"key":"district","name":"行政區"},{"key":"address","name":"FDA地址"},{"key":"vendor_category","name":"業者分類"},{"key":"registration_item","name":"登錄項目"}]
204	food_safety_logistics_vendor_ntpe	新北市食品物流業者	circle	geojson	big	\N	{"circle-color":"#D84C73","circle-radius":["interpolate",["linear"],["zoom"],9,3,12,5,15,8],"circle-opacity":0.72,"circle-stroke-color":"#FFF2F6","circle-stroke-width":1}	[{"key":"name","name":"業者名稱"},{"key":"registration_no","name":"食品業者登錄字號"},{"key":"company_registration_name","name":"公司/商業登記名稱"},{"key":"city","name":"縣市"},{"key":"district","name":"行政區"},{"key":"address","name":"FDA地址"},{"key":"vendor_category","name":"業者分類"},{"key":"registration_item","name":"登錄項目"}]
205	food_safety_health_office_tpe	臺北市衛生監管機構與健康服務中心	circle	geojson	big	\N	{"circle-color":"#2F7D6D","circle-radius":["interpolate",["linear"],["zoom"],9,["case",["==",["get","agency_type"],"衛生局"],6,4],12,["case",["==",["get","agency_type"],"衛生局"],11,7],15,["case",["==",["get","agency_type"],"衛生局"],16,10]],"circle-opacity":0.78,"circle-stroke-color":"#E9FFF8","circle-stroke-width":["case",["==",["get","agency_type"],"衛生局"],2,1.2]}	[{"key":"name","name":"名稱"},{"key":"agency_type","name":"類型"},{"key":"city","name":"縣市"},{"key":"district","name":"行政區"},{"key":"address","name":"地址"},{"key":"phone","name":"電話"},{"key":"website","name":"網址"}]
206	food_safety_health_office_ntpe	新北市衛生監管機構與衛生所	circle	geojson	big	\N	{"circle-color":"#C2573E","circle-radius":["interpolate",["linear"],["zoom"],9,["case",["==",["get","agency_type"],"衛生局"],6,4],12,["case",["==",["get","agency_type"],"衛生局"],11,7],15,["case",["==",["get","agency_type"],"衛生局"],16,10]],"circle-opacity":0.78,"circle-stroke-color":"#FFF1EC","circle-stroke-width":["case",["==",["get","agency_type"],"衛生局"],2,1.2]}	[{"key":"name","name":"名稱"},{"key":"agency_type","name":"類型"},{"key":"city","name":"縣市"},{"key":"district","name":"行政區"},{"key":"address","name":"地址"},{"key":"phone","name":"電話"},{"key":"extension","name":"分機"},{"key":"zipcode","name":"郵遞區號"},{"key":"open_time","name":"服務時間"}]
207	water_quality_tpe	臺北市淨水場水質濁度	circle	geojson	big	\N	{"circle-color":"#1E88E5","circle-radius":["interpolate",["linear"],["coalesce",["to-number",["get","turbidity_ntu"]],0],0,7,0.5,9,1,12],"circle-opacity":0.78,"circle-stroke-color":"#EAF6FF","circle-stroke-width":1.4}	[{"key":"name","name":"淨水場"},{"key":"city","name":"縣市"},{"key":"district","name":"行政區"},{"key":"water_sources","name":"水源"},{"key":"data_time","name":"資料時間"},{"key":"qualified","name":"合格狀態"},{"key":"ph","name":"pH值"},{"key":"turbidity_ntu","name":"濁度(NTU)"},{"key":"free_residual_chlorine_mg_l","name":"自由有效餘氯(mg/L)"},{"key":"total_hardness_mg_l","name":"總硬度(mg/L)"},{"key":"total_dissolved_solids_mg_l","name":"總溶解固體量(mg/L)"},{"key":"coliform_cfu_100ml","name":"大腸桿菌群(CFU/100mL)"}]
208	water_quality_ntpe	新北市淨水場水質濁度	circle	geojson	big	\N	{"circle-color":"#00A6A6","circle-radius":["interpolate",["linear"],["coalesce",["to-number",["get","turbidity_ntu"]],0],0,7,0.5,9,1,12],"circle-opacity":0.78,"circle-stroke-color":"#E8FFFF","circle-stroke-width":1.4}	[{"key":"name","name":"淨水場"},{"key":"english_name","name":"英文名稱"},{"key":"city","name":"縣市"},{"key":"district","name":"行政區"},{"key":"address","name":"地址"},{"key":"data_time","name":"資料時間"},{"key":"qualified","name":"合格狀態"},{"key":"ph","name":"pH值"},{"key":"turbidity_ntu","name":"濁度(NTU)"},{"key":"free_residual_chlorine_mg_l","name":"自由有效餘氯(mg/L)"},{"key":"total_hardness_mg_l","name":"總硬度(mg/L)"},{"key":"total_dissolved_solids_mg_l","name":"總溶解固體量(mg/L)"},{"key":"coliform_cfu_100ml","name":"大腸桿菌群(CFU/100mL)"}]
209	food_source_tpe	臺北市有機農場	circle	geojson	big	\N	{"circle-color":"#30B68F","circle-radius":["interpolate",["linear"],["coalesce",["to-number",["get","area_ha"]],0.1],0,5,0.5,7,1,9,2,12,5,16],"circle-opacity":0.74,"circle-stroke-color":"#F7FFF9","circle-stroke-width":1}	[{"key":"name","name":"農場名稱"},{"key":"operator","name":"農友/經營者"},{"key":"city","name":"縣市"},{"key":"district","name":"行政區"},{"key":"address","name":"地址"},{"key":"certification_no","name":"認證字號"},{"key":"certification_status","name":"驗證狀態"},{"key":"area_ha","name":"面積(公頃)"},{"key":"food_education","name":"食農教育體驗"},{"key":"beekeeping","name":"飼養蜜蜂"},{"key":"chicken_raising","name":"飼養雞隻"}]
210	food_source_ntpe	新北市有機農場	circle	geojson	big	\N	{"circle-color":"#F5B041","circle-radius":["interpolate",["linear"],["coalesce",["to-number",["get","area_ha"]],0.1],0,5,0.5,7,1,9,2,12,5,16],"circle-opacity":0.74,"circle-stroke-color":"#FFF8E8","circle-stroke-width":1}	[{"key":"name","name":"農場名稱"},{"key":"operator","name":"農友/經營者"},{"key":"city","name":"縣市"},{"key":"district","name":"行政區"},{"key":"address","name":"地址"},{"key":"phone","name":"電話"},{"key":"certification_valid_until","name":"有效日期"},{"key":"certification_status","name":"驗證狀態"},{"key":"area_ha","name":"面積(公頃)"}]
301	fda_good_restaurants	優良餐廳	circle	geojson	small	\N	{"circle-color":["match",["get","rating_result"],"優","#8FD9A8","良","#F6D982","#9E9E9E"],"circle-radius":["interpolate",["linear"],["zoom"],9,2,12,3,15,5],"circle-stroke-color":"#ffffff","circle-stroke-width":0.5}	[{"key":"restaurant_name","name":"店名"},{"key":"address","name":"地址"},{"key":"rating_result","name":"評分結果"},{"key":"award_year","name":"年度"}]
\.


--
-- Data for Name: components; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.components (id, index, name) FROM stdin;
60	youbike_availability	YouBike使用情況
213	bike_network	自行車道路統計資料
212	ebus_percent	電動巴士比例
214	dependency_aging	扶養比及老化指數
216	city_age_distribution	全市年齡分區
218	aging_kpi	長照指標
215	aging_workforce_trend	高齡就業人口之年增結構
217	bike_map	自行車道路網圖資
307	food_source	有機農場分布
303	food_safety_market	食品供應市場分布
304	food_safety_logistics_vendor	食品物流業者分布
305	food_safety_health_office	衛生監管機構分布
306	water_quality	淨水廠水質濁度統計
501	fda_good_restaurants	餐飲衛生優良業者分布
502	cdc_infectious_disease	腹瀉就診數據統計
503	food_safety_death_share	主要死因占比統計
505	food_processing_pass_rate	加工食品不合格率統計
\.


--
-- Data for Name: contributors; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.contributors (id, user_id, user_name, image, link, identity, description, include, created_at, updated_at) FROM stdin;
1	doit	臺北市政府資訊局	doit.png	https://doit.gov.taipei/	\N	\N	f	2024-05-09 01:58:47.164185+00	2024-05-09 01:58:47.164185+00
2	ntpc	新北市政府資訊中心	ntpc.png	https://www.imc.ntpc.gov.tw/	\N	\N	f	2024-05-09 01:58:47.164185+00	2024-05-09 01:58:47.164185+00
\.

--
-- Data for Name: dashboards; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.dashboards (id, index, name, components, icon, updated_at, created_at) FROM stdin;
106	map-layers-taipei	圖資資訊	{217}	public	2025-03-12 01:59:00.512775+00	2024-03-21 10:04:24.928533+00
356	ltc_care_tpe	長照關懷	{214,215,216,218}	elderly	2025-02-26 08:43:42.86017+00	2024-03-21 09:38:37.66+00
355	ltc_care_newtpe	長照關懷	{214,215,216,218}	elderly	2025-02-27 06:42:21.705931+00	2024-03-21 09:38:37.66+00
359	map-layers-metrotaipei	圖資資訊	{217}	public	2024-05-16 03:56:12.76016+00	2024-03-21 10:04:24.928533+00
358	practical_transportation_newtpe	務實交通	{60,212,213}	directions_car	2025-03-12 08:00:38.75842+00	2024-03-21 09:38:37.66+00
401	food_safety_health_tpe	食安健康	{307,303,304,305,306,502,503,505}	restaurant	2026-05-02 00:00:00+00	2026-05-02 00:00:00+00
402	food_safety_health_metrotaipei	食安健康	{307,303,304,305,306,501,502,503,505}	restaurant	2026-05-02 00:00:00+00	2026-05-02 00:00:00+00
1	09a25cd9cb7d	收藏組件	\N	favorite	2025-03-14 07:34:22.247753+00	2025-03-14 07:34:22.247753+00
2	3245d9eace5f	我的新儀表板	{215,218,216,213,212,214,60,146}	star	2025-03-14 14:55:11.732116+00	2025-03-14 14:55:11.732116+00
\.


COPY public.groups (id, name, is_personal, create_by) FROM stdin;
1	public	f	\N
2	taipei	f	\N
3	metrotaipei	f	\N
\.


--
-- Data for Name: issues; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.issues (id, title, user_name, user_id, context, description, decision_desc, status, updated_by, created_at, updated_at) FROM stdin;
4	test	Drew	1	test	test	測試	不處理	doit	2024-03-15 07:33:39.695288+00	2024-07-26 06:37:55.038985+00
\.


ALTER TABLE public.query_charts OWNER TO postgres;
TRUNCATE TABLE public.query_charts RESTART IDENTITY CASCADE;
COPY public.query_charts (index, history_config, map_config_ids, map_filter, time_from, time_to, update_freq, update_freq_unit, source, short_desc, long_desc, use_case, links, contributors, created_at, updated_at, query_type, query_chart, query_history, city) FROM stdin;
aging_kpi	\N	{}	{}	static	\N	0	\N	主計處	此圖顯示雙北長照關懷各項指標。	此圖表呈現雙北長照關懷相關指標，包括 扶老比、扶幼比、扶養比 及 老化指數。扶老比代表每百名勞動人口需扶養的老年人口數，扶幼比則是需扶養的兒童人口數，而扶養比則合計這兩者，反映整體社會負擔程度。老化指數則比較老年人口與兒童人口比例，顯示人口結構的高齡化趨勢。這些數據可用於評估長照需求，並規劃資源分配與政策方向，以因應人口老化帶來的挑戰。	在制定長照政策時，政府可運用 扶老比、扶幼比、扶養比 及 老化指數 來評估未來照護需求。例如，某城市發現扶老比上升且老化指數超過 100，代表老年人口已多於兒童，預示長照需求將持續增加。政府可據此增設長照機構、強化居家照護服務，並鼓勵社區共融計畫，以減輕勞動人口的扶養壓力，確保高齡者獲得適切照顧。	{https://data.taipei/dataset/detail?id=64c8a3a0-3b9a-4f49-a13a-fb1eb2ffa4b1,https://data.ntpc.gov.tw/datasets/8308ab58-62d1-424e-8314-24b65b7ab492}	{doit,ntpc}	2023-12-20 05:56:00+00	2024-06-12 06:02:41.642+00	three_d	select y_axis,icon ,round(avg(data))data  \r\nfrom(\r\nselect '扶老比' as y_axis, percent30 as data ,'%' as icon \r\nfrom public.city_age_distribution_taipei \r\nwhere 年份= (select max(年份) from public.city_age_distribution_taipei ) and  區域別='總計' and 統計類型='計'\r\nunion all\r\nselect '扶幼比' as y_axis, percent31 as data ,'%' as icon \r\nfrom public.city_age_distribution_taipei \r\nwhere 年份= (select max(年份) from public.city_age_distribution_taipei ) and  區域別='總計' and 統計類型='計'\r\nunion all\r\nselect '扶養比' as y_axis, percent32 as data ,'%' as icon \r\nfrom public.city_age_distribution_taipei \r\nwhere 年份= (select max(年份) from public.city_age_distribution_taipei ) and  區域別='總計' and 統計類型='計'\r\nunion all\r\nselect '老化指數' as y_axis, percent33 as data ,'%' as icon \r\nfrom public.city_age_distribution_taipei \r\nwhere 年份= (select max(年份) from public.city_age_distribution_taipei ) and  區域別='總計' and 統計類型='計'\r\nunion all\r\nselect '扶老比' as y_axis, avg(percent30) as data ,'%' as icon \r\nfrom public.city_age_distribution_newtaipei \r\nwhere 年份= (select max(年份) from public.city_age_distribution_newtaipei )  and 統計類型='計'\r\nunion all\r\nselect '扶幼比' as y_axis, avg(percent31) as data ,'%' as icon \r\nfrom public.city_age_distribution_newtaipei \r\nwhere 年份= (select max(年份) from public.city_age_distribution_newtaipei ) and 統計類型='計'\r\nunion all\r\nselect '扶養比' as y_axis, avg(percent32) as data ,'%' as icon \r\nfrom public.city_age_distribution_newtaipei \r\nwhere 年份= (select max(年份) from public.city_age_distribution_newtaipei )  and 統計類型='計'\r\nunion all\r\nselect '老化指數' as y_axis, avg(percent33) as data ,'%' as icon \r\nfrom public.city_age_distribution_newtaipei \r\nwhere 年份= (select max(年份) from public.city_age_distribution_newtaipei )  and 統計類型='計'\r\n)d\r\ngroup by y_axis,icon	\N	metrotaipei
aging_kpi	\N	{}	{}	static	\N	0	\N	主計處	此圖顯示臺北長照關懷各項指標。	此圖表呈現臺北長照關懷相關指標，包括 扶老比、扶幼比、扶養比 及 老化指數。扶老比代表每百名勞動人口需扶養的老年人口數，扶幼比則是需扶養的兒童人口數，而扶養比則合計這兩者，反映整體社會負擔程度。老化指數則比較老年人口與兒童人口比例，顯示人口結構的高齡化趨勢。這些數據可用於評估長照需求，並規劃資源分配與政策方向，以因應人口老化帶來的挑戰。	在制定長照政策時，政府可運用 扶老比、扶幼比、扶養比 及 老化指數 來評估未來照護需求。例如，某城市發現扶老比上升且老化指數超過 100，代表老年人口已多於兒童，預示長照需求將持續增加。政府可據此增設長照機構、強化居家照護服務，並鼓勵社區共融計畫，以減輕勞動人口的扶養壓力，確保高齡者獲得適切照顧。	{https://data.taipei/dataset/detail?id=64c8a3a0-3b9a-4f49-a13a-fb1eb2ffa4b1}	{doit}	2023-12-20 05:56:00+00	2024-06-12 06:02:41.642+00	three_d	select y_axis,icon ,round(avg(data))data  \r\nfrom(\r\nselect '扶老比' as y_axis, percent30 as data ,'%' as icon \r\nfrom public.city_age_distribution_taipei \r\nwhere 年份= (select max(年份) from public.city_age_distribution_taipei ) and  區域別='總計' and 統計類型='計'\r\nunion all\r\nselect '扶幼比' as y_axis, percent31 as data ,'%' as icon \r\nfrom public.city_age_distribution_taipei \r\nwhere 年份= (select max(年份) from public.city_age_distribution_taipei ) and  區域別='總計' and 統計類型='計'\r\nunion all\r\nselect '扶養比' as y_axis, percent32 as data ,'%' as icon \r\nfrom public.city_age_distribution_taipei \r\nwhere 年份= (select max(年份) from public.city_age_distribution_taipei ) and  區域別='總計' and 統計類型='計'\r\nunion all\r\nselect '老化指數' as y_axis, percent33 as data ,'%' as icon \r\nfrom public.city_age_distribution_taipei \r\nwhere 年份= (select max(年份) from public.city_age_distribution_taipei ) and  區域別='總計' and 統計類型='計'\r\n)d\r\ngroup by y_axis,icon	\N	taipei
aging_workforce_trend	\N	\N	\N	static	\N	\N	\N	主計處	顯示雙北就業人口之年齡結構時間數列統計資料	雙北地區人口年齡分配按月別時間數列統計資料，記錄臺北市與新北市各年齡層人口數的月度變化，涵蓋從0歲至65歲以上等多個年齡區間。該資料反映雙北地區人口在不同年齡層之分布情形，具備連續性與時間性，可作為分析區域人口結構、行政規劃及社會資源配置的重要參考。透過長期追蹤，亦能協助了解人口構成在不同時間點的變化狀況與組成比例，有助於支持各項人口相關研究與實務應用。	適用於跨域分析或探討都市群體共通趨勢，涵蓋臺北市與新北市兩地，常見於區域整體發展、通勤流動、就業市場整合、住宅與交通規劃等議題。亦可用於比較兩市人口結構差異、公共資源分布或整合性施政評估。例如：雙北地區勞動參與率變化、雙北通勤族群結構分析、雙北教育資源均衡程度探討等。	{https://data.taipei/dataset/detail?id=df320c78-f66b-4504-92b4-cf2a2eb46f1b,https://data.ntpc.gov.tw/datasets/c285509a-7fb2-434f-8542-0b4986c337a8}	{doit,ntpc}	2024-11-28 05:56:00+00	2024-12-10 02:59:39.341+00	three_d	select x_axis,y_axis,round(avg(percentage)) as data\r\nfrom (select year as x_axis,'1.非高齡就業人口' as y_axis,sum(percentage) as percentage  from employment_age_structure_tpe\r\nwhere  gender ='總計' and age_structure not in ('就業人口','就業人口按年齡別/45-49歲','就業人口按年齡別/50-54歲','就業人口按年齡別/55-59歲','就業人口按年齡別/60-64歲','就業人口按年齡別/65歲以上')\r\ngroup by year \r\nunion all \r\nselect year as x_axis,'2.中高齡就業人口' as y_axis,percentage as data  from employment_age_structure_tpe\r\nwhere  gender ='總計' and age_structure  in ('就業人口按年齡別/45-49歲','就業人口按年齡別/50-54歲','就業人口按年齡別/55-59歲','就業人口按年齡別/60-64歲')\r\nunion all \r\nselect year as x_axis,'3.高齡就業人口' as y_axis,percentage as data  from employment_age_structure_tpe\r\nwhere  gender ='總計' and age_structure  in ('就業人口按年齡別/65歲以上')\r\nunion all \r\nselect year as x_axis,'1.非高齡就業人口' as y_axis,sum(percentage) as data  from employment_age_structure_new_tpe\r\nwhere  gender ='總計' and age_structure not in ('就業人口','就業人口按年齡別/45-49歲','就業人口按年齡別/50-54歲','就業人口按年齡別/55-59歲','就業人口按年齡別/60-64歲','就業人口按年齡別/65歲以上')\r\ngroup by year \r\nunion all \r\nselect year as x_axis,'2.中高齡就業人口' as y_axis,percentage as data  from employment_age_structure_new_tpe\r\nwhere  gender ='總計' and age_structure  in ('就業人口按年齡別/45-49歲','就業人口按年齡別/50-54歲','就業人口按年齡別/55-59歲','就業人口按年齡別/60-64歲')\r\nunion all \r\nselect year as x_axis,'3.高齡就業人口' as y_axis,percentage as data  from employment_age_structure_new_tpe\r\nwhere  gender ='總計' and age_structure  in ('就業人口按年齡別/65歲以上'))d\r\nwhere x_axis >'2016'\r\ngroup by x_axis,y_axis \r\norder by 1,2	\N	metrotaipei
aging_workforce_trend	\N	\N	\N	static	\N	\N	\N	主計處	顯示臺北就業人口之年齡結構時間數列統計資料	臺北市人口年齡分配按月別時間數列統計資料，提供各年齡層人口數的定期統計結果，依月別呈現，涵蓋從幼年、青壯年至高齡等不同年齡區間。此資料可作為觀察人口結構組成的重要依據，反映各年齡層在人口總數中的分布情形。透過持續的月別紀錄，可供相關單位進行人口結構分析、資源分配規劃及政策評估等多元應用。資料內容具體、連續，適合用於進行長期與跨時比較之研究分析。	適用於聚焦單一行政區之人口、就業、教育、社會福利、都市規劃等議題。多用於市政層級的政策分析、市內人口結構觀察、社會服務配置研究，以及針對臺北市特定區域（如中正區、大安區等）的細部分析。例如：臺北市高齡人口比例變化、臺北市各區幼兒園分布狀況等。	{https://data.taipei/dataset/detail?id=df320c78-f66b-4504-92b4-cf2a2eb46f1b}	{doit}	2024-11-28 05:56:00+00	2025-03-19 10:25:55.340887+00	three_d	select x_axis,y_axis,round(avg(percentage)) as data\r\nfrom (select year as x_axis,'1.非高齡就業人口' as y_axis,sum(percentage) as percentage  from employment_age_structure_tpe\r\nwhere  gender ='總計' and age_structure not in ('就業人口','就業人口按年齡別/45-49歲','就業人口按年齡別/50-54歲','就業人口按年齡別/55-59歲','就業人口按年齡別/60-64歲','就業人口按年齡別/65歲以上')\r\ngroup by year \r\nunion all \r\nselect year as x_axis,'2.中高齡就業人口' as y_axis,percentage as data  from employment_age_structure_tpe\r\nwhere  gender ='總計' and age_structure  in ('就業人口按年齡別/45-49歲','就業人口按年齡別/50-54歲','就業人口按年齡別/55-59歲','就業人口按年齡別/60-64歲')\r\nunion all \r\nselect year as x_axis,'3.高齡就業人口' as y_axis,percentage as data  from employment_age_structure_tpe\r\nwhere  gender ='總計' and age_structure  in ('就業人口按年齡別/65歲以上')\r\n)d\r\nwhere x_axis >'2016'\r\ngroup by x_axis,y_axis \r\norder by 1,2	\N	taipei
bike_map	\N	{100,101}	{}	static	\N	\N	\N	交通局交工處	顯示雙北當前自行車路網分布。	顯示雙北當前自行車路網分布。雙北擁有完善的自行車路網，主要包括河濱自行車道和市區自行車道。河濱自行車道沿淡水河、基隆河、新店溪和景美溪等河岸建設，提供連續且風景優美的騎行路線。市區自行車道則遍布於主要道路，如敦化南北路、成功路、承德路、松隆路、松德路、和平西路、民生東路、北安路、金湖路、八德路、大道路、光復南路和永吉路等，方便市民在城市中安全騎行。此外，雙北政府持續推動「自行車道願景計畫」，以串聯既有路網、銜接跨市及河濱自行車道，並優化現有自行車道，提升騎行環境的便利性與安全性。	使用於地圖分析、交通規劃與旅遊建議，雙北的自行車路網可與其他圖資套疊，提供更深入的洞察。透過將自行車道與人口密度、交通流量或公車捷運路線交叉比對，可優化城市規劃，提高自行車友善程度。對於旅遊應用，可將自行車道與景點、商圈、飯店位置結合，推薦最佳騎行路線，提升遊憩體驗。此外，政府與企業可藉由數據分析發掘需求熱點，進一步優化自行車基礎設施與共享單車系統。	{https://tdx.transportdata.tw/api/basic/v2/Cycling/Shape/City/Taipei?%24top=30&%24format=JSON,https://tdx.transportdata.tw/api/basic/v2/Cycling/Shape/City/NewTaipei?%24top=30&%24format=JSON}	{doit,ntpc}	2023-12-20 05:56:00+00	2024-01-11 06:26:02.069+00	map_legend	SELECT unnest(array['自行車路網']) as name, 'line' as type	\N	metrotaipei
bike_map	\N	{100}	{}	static	\N	\N	\N	交通局交工處	顯示臺北當前自行車路網分布。	顯示臺北市當前自行車路網分布。臺北市擁有完善的自行車路網，主要由河濱自行車道與市區自行車道組成。河濱自行車道沿淡水河、基隆河、新店溪與景美溪等河岸規劃，提供連續、寬敞且景觀良好的騎行空間，深受市民與遊客喜愛。市區自行車道則分布於市內多條主要幹道，包括敦化南北路、承德路、松隆路、松德路、和平西路、民生東路、八德路、光復南路、永吉路等，串聯重要商圈、學區與轉運點，提升日常通勤與短程移動的便利性。臺北市政府持續推動「自行車道願景計畫」，整合市區與河濱車道系統、銜接捷運與轉乘據點，並優化既有路線與設施，致力打造友善、安全的騎乘環境。	使用於地圖分析、交通規劃與旅遊建議，雙北的自行車路網可與其他圖資套疊，提供更深入的洞察。透過將自行車道與人口密度、交通流量或公車捷運路線交叉比對，可優化城市規劃，提高自行車友善程度。對於旅遊應用，可將自行車道與景點、商圈、飯店位置結合，推薦最佳騎行路線，提升遊憩體驗。此外，政府與企業可藉由數據分析發掘需求熱點，進一步優化自行車基礎設施與共享單車系統。	{https://tdx.transportdata.tw/api/basic/v2/Cycling/Shape/City/Taipei?%24top=30&%24format=JSON}	{doit}	2023-12-20 05:56:00+00	2024-01-11 06:26:02.069+00	map_legend	SELECT unnest(array['自行車路網']) as name, 'line' as type	\N	taipei
food_source	\N	{209,210}	{"mode":"byParam","byParam":{"xParam":"district"}}	static	\N	\N	\N	臺北市政府產業發展局、新北市政府農業局	顯示雙北有機農場分布。	顯示臺北市取得有機驗證之有機農場與新北市有機農場之空間分布，並以行政區圖、矩形圖與橫向長條圖呈現各行政區有機農場數量。資料包含農場名稱、經營者、行政區、地址、驗證狀態、面積與聯絡資訊；地址可定位者使用地址座標，地號或無法定位者以行政區中心點加微小偏移顯示，作為有機農場與食安供應鏈節點盤點基礎。	可用於掌握雙北有機農產品來源分布、食安供應鏈來源追蹤、產地與市場或物流節點套疊分析，以及農業資源與稽查服務配置。	{https://data.taipei/dataset/detail?id=32aea2da-14a7-47b6-a687-57e29c1ad4a7,https://data.ntpc.gov.tw/datasets/fc30f585-66d9-4233-a65e-c650d177ebfe}	{doit,ntpc}	2026-05-02 00:00:00+00	2026-05-02 00:00:00+00	two_d	SELECT x_axis, SUM(data)::int AS data FROM (SELECT district AS x_axis, COUNT(*)::int AS data FROM public.food_source_tpe WHERE district != '' GROUP BY district UNION ALL SELECT district AS x_axis, COUNT(*)::int AS data FROM public.food_source_ntpe WHERE district != '' GROUP BY district) d GROUP BY x_axis ORDER BY data DESC	\N	metrotaipei
food_source	\N	{209}	{"mode":"byParam","byParam":{"xParam":"district"}}	static	\N	\N	\N	臺北市政府產業發展局	顯示臺北市有機農場分布。	顯示臺北市取得有機驗證之有機農場空間分布，並以行政區圖、矩形圖與橫向長條圖呈現各行政區有機農場數量。資料包含農場名稱、農友姓名、行政區、地址、認證字號、面積與食農教育等欄位；地址可定位者使用地址座標，無法定位者以行政區中心點加微小偏移顯示，作為有機農場與食安供應鏈節點盤點基礎。	可用於掌握臺北市有機農產品來源分布、食安供應鏈來源追蹤、產地與市場或物流節點套疊分析，以及農業資源與稽查服務配置。	{https://data.taipei/dataset/detail?id=32aea2da-14a7-47b6-a687-57e29c1ad4a7}	{doit}	2026-05-02 00:00:00+00	2026-05-02 00:00:00+00	two_d	SELECT district AS x_axis, COUNT(*)::int AS data FROM public.food_source_tpe WHERE district != '' GROUP BY district ORDER BY data DESC	\N	taipei
food_safety_market	\N	{201,202}	{}	static	\N	\N	\N	臺北市市場處、新北市政府市場處	顯示雙北公有市場分布與攤位類型統計。	顯示臺北市各區公有零售市(商)場與新北市公有市場名冊之空間分布，並以圓餅圖、矩形圖與橫向長條圖呈現公有市場攤位類型彙總。臺北資料包含市場名稱、行政區與各營業種類攤位數，新北資料包含市場名稱、行政區、地址、電話與市場型態；資料經批次地理編碼後轉為地圖點位，提供市場分布、攤位結構與食安巡檢、公共衛生資源配置的基礎圖資。	可用於食安稽查排程、市場周邊公共衛生服務配置、跨區市場分布比較、攤位營業類型結構分析，以及與人口、交通、醫療或災防圖層套疊分析，協助掌握民生採買場域與健康風險管理的空間關係。	{https://data.taipei/dataset/detail?id=f490476d-d156-4492-a463-cf3405de3b55,https://data.ntpc.gov.tw/datasets/785be91a-caaf-4e1c-91d6-f7d616d31a45}	{doit,ntpc}	2026-05-02 00:00:00+00	2026-05-02 00:00:00+00	two_d	SELECT unnest(array['百貨花卉','蔬果','糧食雜貨','肉禽','飲食','水產','其他','空攤']) as x_axis, unnest(array[2205,1659,1463,1381,1086,851,848,144]) as data	\N	metrotaipei
food_safety_market	\N	{201}	{}	static	\N	\N	\N	臺北市市場處	顯示臺北市公有市場分布與攤位類型統計。	顯示臺北市各區公有零售市(商)場之空間分布，並以圓餅圖、矩形圖與橫向長條圖呈現攤位類型彙總；資料包含市場名稱、行政區與各營業種類攤位數，並經批次地理編碼後轉為地圖點位，提供市場分布、攤位結構與食安巡檢、公共衛生資源配置的基礎圖資。	可用於食安稽查排程、市場周邊公共衛生服務配置、行政區市場分布比較、攤位營業類型結構分析，以及與人口、交通、醫療或災防圖層套疊分析。	{https://data.taipei/dataset/detail?id=f490476d-d156-4492-a463-cf3405de3b55}	{doit}	2026-05-02 00:00:00+00	2026-05-02 00:00:00+00	two_d	SELECT unnest(array['百貨花卉','蔬果','糧食雜貨','肉禽','飲食','水產','其他']) as x_axis, unnest(array[1876,1305,1067,951,663,621,592]) as data	\N	taipei
food_safety_logistics_vendor	\N	{203,204}	{}	static	\N	\N	\N	衛生福利部食品藥物管理署	顯示雙北食品物流業者行政區分布。	顯示 FDA 食品業者登錄中分類為物流業的雙北業者行政區分布，並以行政區圖、矩形圖與橫向長條圖呈現各行政區業者數量。資料由縣市列表端點以 tp=6 抓取，因來源未提供業者經緯度，臺北市地圖先以臺北市門牌位置數值資料定位，未成功者再使用地址轉座標與 OpenStreetMap 道路/地名定位，最後才以行政區中心點加微小偏移顯示每筆業者，並提供業者名稱、登錄字號、地址等欄位。	可用於食安物流節點分布盤點、稽查資源配置、行政區風險熱點比較，以及與市場、人口、交通圖層套疊分析。	{https://fadenbook.fda.gov.tw/pub/search-Vendor-County-result.aspx?city=%E8%87%BA%E5%8C%97%E5%B8%82,https://fadenbook.fda.gov.tw/pub/search-Vendor-County-result.aspx?city=%E6%96%B0%E5%8C%97%E5%B8%82}	{doit,ntpc}	2026-05-02 00:00:00+00	2026-05-02 00:00:00+00	two_d	SELECT unnest(array['新莊區','五股區','中山區','汐止區','中和區','樹林區','林口區','松山區','三重區','內湖區','萬華區','板橋區','士林區','新店區','土城區','八里區','南港區','大安區','信義區','北投區','三峽區','瑞芳區','鶯歌區','中正區','蘆洲區','泰山區','大同區','淡水區','文山區','永和區','三芝區','深坑區']) as x_axis, unnest(array[63,60,53,50,48,36,34,31,29,29,29,28,27,25,24,22,21,19,14,13,11,11,10,9,9,8,7,6,4,3,1,1]) as data	\N	metrotaipei
food_safety_logistics_vendor	\N	{203}	{}	static	\N	\N	\N	衛生福利部食品藥物管理署	顯示臺北市食品物流業者行政區分布。	顯示 FDA 食品業者登錄中分類為物流業的臺北市業者行政區分布，並以行政區圖、矩形圖與橫向長條圖呈現各行政區業者數量。資料由縣市列表端點以 tp=6 抓取，因來源未提供業者經緯度，地圖先以臺北市門牌位置數值資料定位，未成功者再使用地址轉座標與 OpenStreetMap 道路/地名定位，最後才以行政區中心點加微小偏移顯示每筆業者，並提供業者名稱、登錄字號、地址等欄位。	可用於食安物流節點分布盤點、稽查資源配置、行政區風險熱點比較，以及與市場、人口、交通圖層套疊分析。	{https://fadenbook.fda.gov.tw/pub/search-Vendor-County-result.aspx?city=%E8%87%BA%E5%8C%97%E5%B8%82}	{doit}	2026-05-02 00:00:00+00	2026-05-02 00:00:00+00	two_d	SELECT unnest(array['中山區','松山區','內湖區','萬華區','士林區','南港區','大安區','信義區','北投區','中正區','大同區','文山區']) as x_axis, unnest(array[53,31,29,29,27,21,19,14,13,9,7,4]) as data	\N	taipei
food_safety_health_office	\N	{205,206}	{}	static	\N	\N	\N	臺北市政府衛生局、新北市政府衛生局	顯示雙北衛生監管機構服務據點類型統計。	顯示臺北市政府衛生局、臺北市健康服務中心、新北市政府衛生局與新北市各區衛生所之空間分布，並以圓餅圖、矩形圖與橫向長條圖呈現各類型據點數量；包含名稱、行政區、地址、電話、服務時間或網站等資訊。臺北市點位優先使用臺北市門牌位置數值資料定位，新北市點位使用 OpenStreetMap 道路/地名定位。	可用於食安稽查支援、衛生服務據點查找、公共衛生資源配置、食品安全事件應變聯絡與跨區服務覆蓋分析。	{https://data.gov.tw/dataset/121146,https://data.gov.tw/dataset/125693,https://health.gov.taipei/,https://www.health.ntpc.gov.tw/}	{doit,ntpc}	2026-05-02 00:00:00+00	2026-05-02 00:00:00+00	two_d	SELECT unnest(array['衛生所','健康服務中心','衛生監管機構']) as x_axis, unnest(array[29,12,2]) as data	\N	metrotaipei
food_safety_health_office	\N	{205}	{}	static	\N	\N	\N	臺北市政府衛生局	顯示臺北市衛生監管機構與健康服務中心類型統計。	顯示臺北市政府衛生局與各區健康服務中心之空間分布，並以圓餅圖、矩形圖與橫向長條圖呈現各類型據點數量；包含名稱、行政區、地址、電話與網站等資訊。點位優先使用臺北市門牌位置數值資料定位。	可用於食安稽查支援、衛生服務據點查找、公共衛生資源配置與食品安全事件應變聯絡。	{https://data.gov.tw/dataset/121146,https://health.gov.taipei/}	{doit}	2026-05-02 00:00:00+00	2026-05-02 00:00:00+00	two_d	SELECT unnest(array['健康服務中心','衛生監管機構']) as x_axis, unnest(array[12,1]) as data	\N	taipei
water_quality	\N	{207,208}	{}	static	\N	\N	\N	臺北市政府主計處、臺灣自來水股份有限公司	顯示雙北淨水場水質濁度比較。	顯示臺北自來水淨水場清水水質年度統計，以及臺灣自來水公司平均水質中關鍵字為新北市的淨水場最新測值；總覽以橫向長條圖比較各淨水場濁度(NTU)，並在地圖點位中提供 pH、濁度、自由有效餘氯、總硬度、總溶解固體量與大腸桿菌群等欄位。	可用於掌握飲用水供應節點水質狀態，與市場、食品物流、衛生服務據點套疊，支援食安健康監測、跨區供水風險盤點與公共衛生應變。	{https://data.taipei/dataset/detail?id=9626c65d-8fe7-45bb-bbe2-7439bed81010,https://www.water.gov.tw/ch/WaterQuality?nodeId=4631}	{doit,ntpc}	2026-05-02 00:00:00+00	2026-05-02 00:00:00+00	two_d	SELECT name AS x_axis, turbidity_ntu::float AS data FROM (SELECT name, turbidity_ntu FROM public.water_quality_tpe UNION ALL SELECT name, turbidity_ntu FROM public.water_quality_ntpe) d WHERE turbidity_ntu IS NOT NULL ORDER BY data DESC, x_axis	\N	metrotaipei
water_quality	\N	{207}	{}	static	\N	\N	\N	臺北市政府主計處	顯示臺北市淨水場水質濁度比較。	顯示臺北自來水淨水場清水水質年度統計；總覽以橫向長條圖比較各淨水場濁度(NTU)，並在地圖點位中提供 pH、濁度、自由有效餘氯、總硬度、總溶解固體量與大腸桿菌群等欄位。	可用於掌握臺北飲用水供應節點水質狀態，與市場、食品物流、衛生服務據點套疊，支援食安健康監測與公共衛生應變。	{https://data.taipei/dataset/detail?id=9626c65d-8fe7-45bb-bbe2-7439bed81010}	{doit}	2026-05-02 00:00:00+00	2026-05-02 00:00:00+00	two_d	SELECT name AS x_axis, turbidity_ntu::float AS data FROM public.water_quality_tpe WHERE turbidity_ntu IS NOT NULL ORDER BY data DESC, x_axis	\N	taipei
fda_good_restaurants	\N	{301}	{"mode":"byParam","byParam":{"xParam":"district"}}	static	\N	\N	\N	衛生監管機構	顯示雙北最新年度評核結果為優或良的優良餐廳點位。	此圖層彙整臺北市與新北市最新年度優良餐廳資料，包含店名、地址、經緯度與評分結果，並僅保留資料來源可取得之最新年度資料。	可用於食安健康服務查詢、餐飲環境品質觀察、商圈餐飲設施盤點，以及與人口、交通或觀光圖層套疊分析。	{https://foodtracer.health.ntpc.gov.tw/w/foodtracer/FoodAward,https://data.gov.tw/dataset/145738}	{doit,ntpc}	2026-05-02 00:00:00+00	2026-05-02 00:00:00+00	three_d	WITH district_order(district, sort_order) AS (VALUES ('北投區',1),('士林區',2),('內湖區',3),('南港區',4),('松山區',5),('信義區',6),('中山區',7),('大同區',8),('中正區',9),('萬華區',10),('大安區',11),('文山區',12),('新莊區',13),('淡水區',14),('汐止區',15),('板橋區',16),('三重區',17),('樹林區',18),('土城區',19),('蘆洲區',20),('中和區',21),('永和區',22),('新店區',23),('鶯歌區',24),('三峽區',25),('瑞芳區',26),('五股區',27),('泰山區',28),('林口區',29),('深坑區',30),('石碇區',31),('坪林區',32),('三芝區',33),('石門區',34),('八里區',35),('平溪區',36),('雙溪區',37),('貢寮區',38),('金山區',39),('萬里區',40),('烏來區',41)), ratings(rating_result, rating_order) AS (VALUES ('優',1),('良',2)), aggregated AS (SELECT district, rating_result, COUNT(*)::int AS data FROM public.fda_good_restaurants WHERE award_year = (SELECT MAX(award_year) FROM public.fda_good_restaurants) GROUP BY district, rating_result) SELECT d.district AS x_axis, r.rating_result AS y_axis, COALESCE(a.data, 0)::int AS data FROM district_order d CROSS JOIN ratings r LEFT JOIN aggregated a ON a.district = d.district AND a.rating_result = r.rating_result ORDER BY d.sort_order, r.rating_order	\N	metrotaipei
cdc_infectious_disease	{"range":["max"],"color":["#4CB495","#F5C860","#ED6A45"],"unit":"人次"}	{}	{}	static	\N	1	week	衛生福利部疾病管制署	顯示臺北市近 12 週腹瀉門診、住院及急診就診人次。	此組件彙整 CDC 腹瀉健保門診及住院就診人次統計與急性腹瀉急診傳染病監測統計；資料篩選 2016 至 2026 年，並以 ISO week 週一日期作為週資料時間。主圖顯示近 12 週，歷史圖以年份加總呈現。	可用於觀察食安健康相關腸胃道症狀近期週變化與年度趨勢，輔助公共衛生監測與疫情風險溝通。	{https://od.cdc.gov.tw/eic/NHI_Diarrhea.csv,https://od.cdc.gov.tw/eic/RODS_AcuteDiarrhea.csv}	{doit}	2026-05-02 00:00:00+00	2026-05-02 00:00:00+00	three_d	WITH latest_weeks AS (SELECT DISTINCT data_time FROM public.cdc_infectious_disease WHERE county = '臺北市' ORDER BY data_time DESC LIMIT 12), weeks AS (SELECT data_time FROM latest_weeks ORDER BY data_time), visit_types(visit_type, sort_order) AS (VALUES ('門診', 1), ('住院', 2), ('急診', 3)) SELECT TO_CHAR(w.data_time, 'YYYY-MM-DD') AS x_axis, v.visit_type AS y_axis, COALESCE(SUM(d.patient_visit), 0)::float AS data FROM weeks w CROSS JOIN visit_types v LEFT JOIN public.cdc_infectious_disease d ON d.data_time = w.data_time AND d.visit_type = v.visit_type AND d.county = '臺北市' GROUP BY w.data_time, v.visit_type, v.sort_order ORDER BY w.data_time, v.sort_order	WITH visit_types(visit_type, sort_order) AS (VALUES ('門診', 1), ('住院', 2), ('急診', 3)) SELECT MAKE_DATE(d.year, 1, 1)::timestamp AS x_axis, v.visit_type AS y_axis, SUM(d.patient_visit)::float AS data FROM public.cdc_infectious_disease d JOIN visit_types v ON d.visit_type = v.visit_type WHERE d.county = '臺北市' AND d.year BETWEEN 2016 AND 2026 GROUP BY d.year, v.visit_type, v.sort_order ORDER BY d.year, v.sort_order	taipei
cdc_infectious_disease	{"range":["max"],"color":["#4CB495","#F5C860","#ED6A45"],"unit":"人次"}	{}	{}	static	\N	1	week	衛生福利部疾病管制署	顯示雙北近 12 週腹瀉門診、住院及急診就診人次。	此組件彙整 CDC 腹瀉健保門診及住院就診人次統計與急性腹瀉急診傳染病監測統計；資料篩選 2016 至 2026 年，並以 ISO week 週一日期作為週資料時間。雙北版本聚合臺北市與新北市，主圖顯示近 12 週，歷史圖以年份加總呈現。	可用於觀察雙北食安健康相關腸胃道症狀近期週變化與年度趨勢，輔助公共衛生監測、疫情風險溝通與跨區比較。	{https://od.cdc.gov.tw/eic/NHI_Diarrhea.csv,https://od.cdc.gov.tw/eic/RODS_AcuteDiarrhea.csv}	{doit}	2026-05-02 00:00:00+00	2026-05-02 00:00:00+00	three_d	WITH latest_weeks AS (SELECT DISTINCT data_time FROM public.cdc_infectious_disease WHERE county IN ('臺北市', '新北市') ORDER BY data_time DESC LIMIT 12), weeks AS (SELECT data_time FROM latest_weeks ORDER BY data_time), visit_types(visit_type, sort_order) AS (VALUES ('門診', 1), ('住院', 2), ('急診', 3)) SELECT TO_CHAR(w.data_time, 'YYYY-MM-DD') AS x_axis, v.visit_type AS y_axis, COALESCE(SUM(d.patient_visit), 0)::float AS data FROM weeks w CROSS JOIN visit_types v LEFT JOIN public.cdc_infectious_disease d ON d.data_time = w.data_time AND d.visit_type = v.visit_type AND d.county IN ('臺北市', '新北市') GROUP BY w.data_time, v.visit_type, v.sort_order ORDER BY w.data_time, v.sort_order	WITH visit_types(visit_type, sort_order) AS (VALUES ('門診', 1), ('住院', 2), ('急診', 3)) SELECT MAKE_DATE(d.year, 1, 1)::timestamp AS x_axis, v.visit_type AS y_axis, SUM(d.patient_visit)::float AS data FROM public.cdc_infectious_disease d JOIN visit_types v ON d.visit_type = v.visit_type WHERE d.county IN ('臺北市', '新北市') AND d.year BETWEEN 2016 AND 2026 GROUP BY d.year, v.visit_type, v.sort_order ORDER BY d.year, v.sort_order	metrotaipei
food_safety_death_share	\N	{}	{}	static	\N	1	year	臺北市政府主計處	顯示臺北市近 10 年主要死因死亡占比趨勢。	此組件使用臺北市主要死因死亡率資料，將心臟疾病、糖尿病、腎炎腎徵候群及腎性病變、慢性肝病及肝硬化之死亡率除以所有死亡原因死亡率，轉換為占所有死亡原因之百分比，並以近 10 年趨勢作為主圖呈現。此指標是食安健康頁面的慢性病與主要死因背景指標，不代表食安事件直接歸因死亡。	可用於觀察臺北市食安健康相關慢性病背景、與腹瀉就診、食品來源、市場、物流及衛生據點等組件交叉參考，輔助公共衛生風險溝通。	{https://tsis.dbas.gov.taipei/statis/webMain.aspx?sys=220&ymf=8100&kind=21&type=0&funid=A05032801&cycle=4&outmode=12&compmode=0&outkind=1&deflst=2&nzo=1}	{doit}	2026-05-02 00:00:00+00	2026-05-02 00:00:00+00	time	WITH causes(death_cause, sort_order) AS (VALUES ('心臟疾病', 1), ('糖尿病', 2), ('腎炎腎徵候群及腎性病變', 3), ('慢性肝病及肝硬化', 4)), latest_year AS (SELECT MAX(year) AS year FROM public.food_safety_death_cause_share WHERE city = '臺北市') SELECT MAKE_DATE(d.year, 1, 1)::timestamp AS x_axis, c.death_cause AS y_axis, ROUND(d.death_share_percent::numeric, 2)::float AS data FROM public.food_safety_death_cause_share d JOIN causes c ON c.death_cause = d.death_cause CROSS JOIN latest_year y WHERE d.city = '臺北市' AND d.year >= y.year - 9 ORDER BY d.year, c.sort_order	\N	taipei
food_safety_death_share	\N	{}	{}	static	\N	1	year	臺北市政府主計處、新北市政府主計處	顯示雙北近 10 年主要死因死亡占比趨勢。	此組件將臺北市主要死因死亡率與新北市主要死因死亡人數統一轉換為主要死因占所有死亡原因之百分比，並以近 10 年趨勢作為主圖呈現。臺北市以該死因死亡率除以所有死亡原因死亡率；新北市以該死因死亡人數除以所有死亡人數。此指標是食安健康頁面的慢性病與主要死因背景指標，不代表食安事件直接歸因死亡。	可用於比較雙北主要死因占比背景，並與腹瀉就診、食品來源、市場、物流、衛生據點與水質等組件交叉參考，支援公共衛生風險盤點與政策溝通。	{https://tsis.dbas.gov.taipei/statis/webMain.aspx?sys=220&ymf=8100&kind=21&type=0&funid=A05032801&cycle=4&outmode=12&compmode=0&outkind=1&deflst=2&nzo=1,https://data.ntpc.gov.tw/datasets/e490f906-93f0-4fc3-b5b3-fe34fb31d1db}	{doit,ntpc}	2026-05-02 00:00:00+00	2026-05-02 00:00:00+00	time	WITH causes(death_cause, sort_order) AS (VALUES ('心臟疾病', 1), ('糖尿病', 2), ('腎炎腎徵候群及腎性病變', 3), ('慢性肝病及肝硬化', 4)), latest_year AS (SELECT city, MAX(year) AS year FROM public.food_safety_death_cause_share WHERE city IN ('臺北市', '新北市') GROUP BY city) SELECT MAKE_DATE(d.year, 1, 1)::timestamp AS x_axis, c.death_cause || '(' || CASE d.city WHEN '臺北市' THEN '台北' ELSE '新北' END || ')' AS y_axis, ROUND(d.death_share_percent::numeric, 2)::float AS data FROM public.food_safety_death_cause_share d JOIN causes c ON c.death_cause = d.death_cause JOIN latest_year y ON y.city = d.city WHERE d.city IN ('臺北市', '新北市') AND d.year >= y.year - 9 ORDER BY d.year, c.sort_order, CASE d.city WHEN '臺北市' THEN 1 ELSE 2 END	\N	metrotaipei
bike_network	\N	{100,101}	{"mode":"byParam","byParam":{"xParam":"direction"}}	static	\N	\N	\N	交通局交工處	顯示雙北當前自行車路網分布。	顯示雙北當前自行車路網分布。雙北擁有完善的自行車路網，主要包括河濱自行車道和市區自行車道。河濱自行車道沿淡水河、基隆河、新店溪和景美溪等河岸建設，提供連續且風景優美的騎行路線。市區自行車道則遍布於主要道路，如敦化南北路、成功路、承德路、松隆路、松德路、和平西路、民生東路、北安路、金湖路、八德路、大道路、光復南路和永吉路等，方便市民在城市中安全騎行。此外，雙北政府持續推動「自行車道願景計畫」，以串聯既有路網、銜接跨市及河濱自行車道，並優化現有自行車道，提升騎行環境的便利性與安全性。	使用於地圖分析、交通規劃與旅遊建議，雙北的自行車路網可與其他圖資套疊，提供更深入的洞察。透過將自行車道與人口密度、交通流量或公車捷運路線交叉比對，可優化城市規劃，提高自行車友善程度。對於旅遊應用，可將自行車道與景點、商圈、飯店位置結合，推薦最佳騎行路線，提升遊憩體驗。此外，政府與企業可藉由數據分析發掘需求熱點，進一步優化自行車基礎設施與共享單車系統。	{https://tdx.transportdata.tw/api/basic/v2/Cycling/Shape/City/Taipei?%24top=30&%24format=JSON,https://tdx.transportdata.tw/api/basic/v2/Cycling/Shape/City/NewTaipei?%24top=30&%24format=JSON}	{doit,ntpc}	2023-12-20 05:56:00+00	2024-01-11 06:26:02.069+00	two_d	select x_axis,sum(data)data from (select  direction as x_axis ,round(sum(cycling_length)/1000) as data\r\nfrom public.bike_network_tpe  \r\ngroup by direction\r\nunion all\r\nselect  direction as x_axis ,round(sum(cycling_length)/1000) as data\r\nfrom public.bike_network_new_tpe  \r\ngroup by direction\r\n)d\r\nwhere x_axis !=''\r\ngroup by x_axis	\N	metrotaipei
bike_network	\N	{100}	{"mode":"byParam","byParam":{"xParam":"direction"}}	static	\N	\N	\N	交通局交工處	顯示臺北市當前自行車路網分布。	顯示臺北市當前自行車路網分布。臺北市擁有完善的自行車路網，主要包括河濱自行車道和市區自行車道。河濱自行車道沿淡水河、基隆河、新店溪和景美溪等河岸建設，提供連續且風景優美的騎行路線。市區自行車道則遍布於主要道路，如敦化南北路、成功路、承德路、松隆路、松德路、和平西路、民生東路、北安路、金湖路、八德路、大道路、光復南路和永吉路等，方便市民在城市中安全騎行。此外，臺北市政府持續推動「自行車道願景計畫」，以串聯既有路網、銜接跨市及河濱自行車道，並優化現有自行車道，提升騎行環境的便利性與安全性。	使用於地圖分析、交通規劃與旅遊建議，臺北市的自行車路網可與其他圖資套疊，提供更深入的洞察。透過將自行車道與人口密度、交通流量或公車捷運路線交叉比對，可優化城市規劃，提高自行車友善程度。對於旅遊應用，可將自行車道與景點、商圈、飯店位置結合，推薦最佳騎行路線，提升遊憩體驗。此外，政府與企業可藉由數據分析發掘需求熱點，進一步優化自行車基礎設施與共享單車系統。	{https://tdx.transportdata.tw/api/basic/v2/Cycling/Shape/City/Taipei?%24top=30&%24format=JSON}	{doit}	2023-12-20 05:56:00+00	2024-01-11 06:26:02.069+00	two_d	select  direction as x_axis ,round(sum(cycling_length)/1000) as data\r\nfrom public.bike_network_tpe  \r\nwhere direction !=''\r\ngroup by direction	\N	taipei
city_age_distribution	\N	\N	\N	static	\N	\N	\N	主計處	顯示雙北年齡分區	顯示雙北地區年齡分區，將人口依年齡群體劃分至不同城市區域。此分區有助於了解臺北市與新北市在人口結構上的差異與分布情形，包括各行政區的老化程度、青壯年與幼年人口比例，為政策制定者、城市規劃者及研究人員提供精確的分析依據。透過此資料，可進行跨區域的公共資源配置、社區規劃與長期照護服務設計，確保雙北地區在教育、交通、醫療與社福等層面能因應不同年齡層需求，促進整體都市發展的均衡與永續。	使用於城市規劃、社會政策制定及人口統計分析，雙北地區年齡分區數據可協助政府與研究機構掌握人口結構的變化情形。此指標適用於評估各年齡層在臺北市與新北市的區域分布，有助於規劃教育資源配置、醫療設施布建及長照服務佈點。除此之外，企業亦可依據此數據進行市場分析，針對不同年齡族群設計產品與服務，強化區域經營策略的精準度與效益。此資料為雙北區域在政策與產業發展上的重要基礎依據。	{https://data.taipei/dataset/detail?id=1e0c58e9-6aa5-4acb-a5a1-f60bacad60f3,https://data.ntpc.gov.tw/datasets/8308ab58-62d1-424e-8314-24b65b7ab492}	{doit,ntpc}	2024-11-28 05:56:00+00	2025-03-20 01:33:28.634747+00	three_d	select x_axis,y_axis,round(sum(data)/1000) data\r\nfrom(select 區域別 as x_axis,'0_14歲人口數' as y_axis,percent24 as data\r\nfrom \r\npublic.city_age_distribution_taipei \r\nwhere 區域別 != '總計' and 年份=(select max(年份)\r\nfrom \r\npublic.city_age_distribution_taipei)\r\nunion all\r\nselect 區域別 as x_axis,'15_64歲人口數' as y_axis,percent26 as data\r\nfrom \r\npublic.city_age_distribution_taipei \r\nwhere 區域別 != '總計' and 年份=(select max(年份)\r\nfrom \r\npublic.city_age_distribution_taipei)\r\nunion all\r\nselect 區域別 as x_axis,'65歲以上人口數' as y_axis,percent28 as data\r\nfrom \r\npublic.city_age_distribution_taipei \r\nwhere 區域別 != '總計' and 年份=(select max(年份)\r\nfrom \r\npublic.city_age_distribution_taipei)\r\nunion all\r\nselect 區域別 as x_axis,'0_14歲人口數' as y_axis,percent24 as data\r\nfrom \r\npublic.city_age_distribution_newtaipei \r\nwhere 區域別 not in ('總計','新北市') and 年份=(select max(年份)\r\nfrom \r\npublic.city_age_distribution_newtaipei)\r\nunion all\r\nselect 區域別 as x_axis,'15_64歲人口數' as y_axis,percent26 as data\r\nfrom \r\npublic.city_age_distribution_newtaipei \r\nwhere 區域別 not in ('總計','新北市') and 年份=(select max(年份)\r\nfrom \r\npublic.city_age_distribution_newtaipei)  \r\nunion all\r\nselect 區域別 as x_axis,'65歲以上人口數' as y_axis,percent28 as data\r\nfrom \r\npublic.city_age_distribution_newtaipei \r\nwhere 區域別 not in ('總計','新北市') and 年份=(select max(年份)\r\nfrom \r\npublic.city_age_distribution_newtaipei)\r\n)d\r\ngroup by x_axis,y_axis\r\n	\N	metrotaipei
city_age_distribution	\N	\N	\N	static	\N	\N	\N	主計處	顯示臺北市年齡分區	顯示臺北市年齡分區，將市民人口依年齡群體劃分至不同行政區域。此分區有助於掌握各區人口結構分布，包括幼年人口、青壯年人口與高齡人口比例，為政策制定者、城市規劃單位及研究人員提供重要的分析依據。透過此資料，可進行公共資源配置、社區照護設計及設施規劃，確保臺北市在教育、醫療、交通與長照等方面的發展，能更貼近各年齡層居民的實際需求，促進人口結構與城市功能的平衡發展。	使用於城市規劃、社會政策制定及人口統計分析，臺北市年齡分區數據可協助市府機關與研究單位掌握市內人口結構的變化。此指標適用於評估各年齡層在不同行政區的分布情形，有助於規劃教育資源、醫療設施及長照服務的佈局與優化。此外，企業亦可依據此資料進行在地市場分析，針對不同年齡族群設計產品與服務，提升區域經營策略的精準度與實效性，強化對臺北市多元人口需求的回應。\n\n\n\n\n\n\n\n\n	{https://data.taipei/dataset/detail?id=1e0c58e9-6aa5-4acb-a5a1-f60bacad60f3}	{doit}	2024-11-28 05:56:00+00	2025-02-21 07:52:55.450103+00	three_d	select x_axis,y_axis,round(sum(data)/1000) data\r\nfrom(select 區域別 as x_axis,'0_14歲人口數' as y_axis,percent24 as data\r\nfrom \r\npublic.city_age_distribution_taipei \r\nwhere 區域別 != '總計' and 年份=(select max(年份)\r\nfrom \r\npublic.city_age_distribution_taipei)\r\nunion all\r\nselect 區域別 as x_axis,'15_64歲人口數' as y_axis,percent26 as data\r\nfrom \r\npublic.city_age_distribution_taipei \r\nwhere 區域別 != '總計' and 年份=(select max(年份)\r\nfrom \r\npublic.city_age_distribution_taipei)\r\nunion all\r\nselect 區域別 as x_axis,'65歲以上人口數' as y_axis,percent28 as data\r\nfrom \r\npublic.city_age_distribution_taipei \r\nwhere 區域別 != '總計' and 年份=(select max(年份)\r\nfrom \r\npublic.city_age_distribution_taipei)\r\n)d\r\ngroup by x_axis,y_axis\r\n	\N	taipei
dependency_aging	\N	\N	\N	static	\N	\N	\N	主計處	顯示雙北扶養比及老化指數時間數列統計資料	顯示雙北扶養比及老化指數時間數列統計資料。雙北政府主計處提供了扶養比和老化指數資料，詳細記錄了各年齡段人口比例的變化情況。這些資料有助於分析雙北人口結構的演變，評估青壯年人口對幼年和老年人口的扶養負擔，以及社會老化程度。透過這些統計資料，政策制定者和研究人員可以深入了解人口趨勢，為未來的社會福利和經濟發展規劃提供參考。	使用於人口結構分析、社會福利規劃與經濟發展評估，雙北的扶養比與老化指數數據提供決策參考。政府機構可透過這些統計資料評估勞動力供給與社會扶養負擔，進而調整退休政策與醫療資源配置。企業可運用數據研判市場趨勢，規劃銀髮族產品與服務。學術研究則可透過時間序列分析，探討人口老化對經濟與社會的影響，為未來城市發展與人口政策提供科學依據。\r\n	{https://data.taipei/dataset/detail?id=aafb15dc-5508-4091-bd48-a708e60f6698,https://data.ntpc.gov.tw/datasets/8308ab58-62d1-424e-8314-24b65b7ab492}	{doit,ntpc}	2024-11-28 05:56:00+00	2024-12-10 02:59:39.341+00	time	select \r\nx_axis,y_axis,round(avg(data)) data\r\nfrom (\r\nselect TO_TIMESTAMP(end_of_year , 'YYYY-MM-DD HH24:MI:SS.MS') AT TIME ZONE 'Asia/Taipei' AS x_axis,\r\n'扶養比' as y_axis,total_dependency_ratio as data  \r\nfrom \r\ndependency_ratio_and_aging_index_tpe\r\nunion all\r\nselect TO_TIMESTAMP(end_of_year , 'YYYY-MM-DD HH24:MI:SS.MS') AT TIME ZONE 'Asia/Taipei' AS x_axis,\r\n'老化指數' as y_axis ,aging_index \r\nfrom \r\ndependency_ratio_and_aging_index_tpe\r\nunion all\r\nselect TO_TIMESTAMP(end_of_year , 'YYYY-MM-DD HH24:MI:SS.MS') AT TIME ZONE 'Asia/Taipei' AS x_axis,\r\n'扶養比' as y_axis,total_dependency_ratio  \r\nfrom \r\ndependency_ratio_and_aging_index_new_tpe\r\nunion all\r\nselect TO_TIMESTAMP(end_of_year , 'YYYY-MM-DD HH24:MI:SS.MS') AT TIME ZONE 'Asia/Taipei' AS x_axis,\r\n'老化指數' as y_axis ,aging_index \r\nfrom \r\ndependency_ratio_and_aging_index_new_tpe\r\n)d\r\nwhere x_axis >'2013-01-01 00:00:00.000'\r\ngroup by x_axis,y_axis\r\norder by 1\r\n	\N	metrotaipei
dependency_aging	\N	\N	\N	static	\N	\N	\N	主計處	顯示臺北市扶養比及老化指數時間數列統計資料	顯示臺北市扶養比及老化指數時間數列統計資料。臺北市政府主計處提供了扶養比和老化指數資料，詳細記錄了各年齡段人口比例的變化情況。這些資料有助於分析臺北市人口結構的演變，評估青壯年人口對幼年和老年人口的扶養負擔，以及社會老化程度。透過這些統計資料，政策制定者和研究人員可以深入了解人口趨勢，為未來的社會福利和經濟發展規劃提供參考。	使用於人口結構分析、社會福利規劃與經濟發展評估，臺北市的扶養比與老化指數數據提供決策參考。政府機構可透過這些統計資料評估勞動力供給與社會扶養負擔，進而調整退休政策與醫療資源配置。企業可運用數據研判市場趨勢，規劃銀髮族產品與服務。學術研究則可透過時間序列分析，探討人口老化對經濟與社會的影響，為未來城市發展與人口政策提供科學依據。\r\n	{https://data.taipei/dataset/detail?id=aafb15dc-5508-4091-bd48-a708e60f6698}	{doit}	2024-11-28 05:56:00+00	2025-02-25 01:43:21.031142+00	time	select \r\nx_axis,y_axis,round(avg(data)) data\r\nfrom (\r\nselect TO_TIMESTAMP(end_of_year , 'YYYY-MM-DD HH24:MI:SS.MS') AT TIME ZONE 'Asia/Taipei' AS x_axis,\r\n'扶養比' as y_axis,total_dependency_ratio as data  \r\nfrom \r\ndependency_ratio_and_aging_index_tpe\r\nunion all\r\nselect TO_TIMESTAMP(end_of_year , 'YYYY-MM-DD HH24:MI:SS.MS') AT TIME ZONE 'Asia/Taipei' AS x_axis,\r\n'老化指數' as y_axis ,aging_index \r\nfrom \r\ndependency_ratio_and_aging_index_tpe\r\n)d\r\nwhere x_axis >'2013-01-01 00:00:00.000'\r\ngroup by x_axis,y_axis\r\norder by 1\r\n	\N	taipei
ebus_percent	\N	\N	\N	static	\N	\N	\N	交通局	顯示雙北電動公車比例	此圖顯示雙北地區電動公車的比例，呈現臺北市與新北市公車車隊中電動車所占比重，以及近年來電動公車數量的成長情形。圖表比較傳統燃油公車與電動公車的比例變化，並標示雙北兩市政府推動電動化政策、補助措施及其帶來的環保效益。透過這些數據，可評估雙北地區電動公車的普及程度，及其對減碳、空氣品質改善的實質貢獻，進一步作為規劃大臺北地區公共運輸電動化策略的重要依據，推動都會區交通體系朝向低碳永續發展。	可用於評估雙北地區公共運輸電動化進程，透過此圖顯示臺北市與新北市公車系統中電動公車的占比及成長趨勢。圖表比較傳統燃油公車與電動公車的比例變化，並標示雙北兩市推動相關政策、補助措施及其所帶來的環保效益。透過這些數據，可評估雙北地區電動公車的普及率，以及其在減碳排放與空氣品質改善上的具體貢獻，進而作為制定更完善的都會區公共運輸電動化策略的重要依據，推動雙北朝向低碳永續城市目標發展。	{https://tdx.transportdata.tw/api/basic/v2/Bus/Vehicle/City/Taipei?%24top=30&%24format=JSON,https://tdx.transportdata.tw/api/basic/v2/Bus/Vehicle/City/NewTaipei?%24top=30&%24format=JSON}	{doit,ntpc}	2025-02-15 05:56:00+00	2024-02-15 02:59:39.341+00	percent	select '電動公車數量' as x_axis,y_axis,sum(data) data from \r\n(select '電動巴士' as y_axis,count(*) as  data\r\nfrom public.bus_info_new_tpe\r\nwhere plate_numb like 'E%'\r\nunion all\r\nselect '非電動巴士' as y_axis,count(*) as  data\r\nfrom public.bus_info_new_tpe\r\nwhere plate_numb not like 'E%'\r\nunion all\r\nselect '電動巴士' as y_axis,count(*) as  data\r\nfrom public.bus_info_tpe\r\nwhere plate_numb like 'E%'\r\nunion all\r\nselect '非電動巴士' as y_axis,count(*) as  data\r\nfrom public.bus_info_tpe)d\r\ngroup by \r\ny_axis\r\n	\N	metrotaipei
ebus_percent	\N	\N	\N	static	\N	\N	\N	交通局	顯示臺北電動公車比例	此圖顯示臺北市電動公車的比例，呈現全市公車車隊中電動車所占比重，以及近年來電動公車數量的成長情形。圖表比較傳統燃油公車與電動公車的比例變化，並標示臺北市政府推動電動化政策、補助措施及其帶來的環保效益。透過這些數據，可評估臺北市電動公車的普及程度，及其在減碳與空氣品質改善上的貢獻，有助於進一步規劃更完善的公共運輸電動化策略，推動城市交通朝向低碳永續目標邁進。	可用於評估臺北市公共運輸電動化的進程，透過此圖顯示電動公車在市區公車總數中的占比及其成長趨勢。圖表呈現傳統燃油公車與電動公車的比例變化，並標示臺北市政府推動的政策措施、補助方案及相關環保效益等影響因素。透過這些數據，可分析臺北市電動公車的普及程度及其在減碳排放與空氣品質改善方面的貢獻，有助於進一步規劃更完善的公共運輸電動化策略，推動臺北朝向低碳與永續發展的城市目標邁進。	{https://tdx.transportdata.tw/api/basic/v2/Bus/Vehicle/City/Taipei?%24top=30&%24format=JSON}	{doit}	2025-02-15 05:56:00+00	2025-02-20 09:11:21.620625+00	percent	select '電動公車數量' as x_axis,y_axis,sum(data) data from \r\n(\r\nselect '電動巴士' as y_axis,count(*) as  data\r\nfrom public.bus_info_tpe\r\nwhere plate_numb like 'E%'\r\nunion all\r\nselect '非電動巴士' as y_axis,count(*) as  data\r\nfrom public.bus_info_tpe)d\r\ngroup by \r\ny_axis	\N	taipei
youbike_availability	\N	{99}	\N	current	\N	10	minute	交通局	顯示當前雙北共享單車YouBike的使用情況。	顯示雙北地區（臺北市與新北市）當前共享單車 YouBike 的使用情況，格式為可借車輛數／全區車位數。資料來源為兩市交通局公開資料，每5分鐘更新一次，提供即時的車輛可用資訊與站點使用狀況，有助於掌握整體運行效率與民眾使用情形，亦可作為交通管理與營運調度的參考依據。	藉由顯示雙北地區 YouBike 的使用情況，以及觀察可借車輛數約為車柱總數的一半，可大致掌握目前停放於站點與使用中車輛的整體分布情形。使用者亦可透過地圖模式查詢雙北各站點的即時資訊，包括可借車輛數、可還空位數及站點位置，方便規劃路線與掌握使用狀況，提升共享單車的便利性與使用效率。	{https://tdx.transportdata.tw/api-service/swagger/basic/2cc9b888-a592-496f-99de-9ab35b7fb70d#/Bike/BikeApi_Availability_2181,https://tdx.transportdata.tw/api/basic/v2/Bike/Availability/City/NewTaipei?%24top=30&%24format=JSON}	{doit,ntpc}	2023-12-20 05:56:00+00	2024-03-19 06:08:17.99+00	percent	select x_axis,y_axis,sum(data)data\r\nfrom (select '在站車輛' as x_axis, \r\nunnest(ARRAY['可借車輛', '空位']) as y_axis, \r\nunnest(ARRAY[SUM(available_rent_general_bikes), SUM(available_return_bikes)]) as data\r\nfrom tran_ubike_realtime_new_tpe\r\nunion all \r\nselect '在站車輛' as x_axis, \r\nunnest(ARRAY['可借車輛', '空位']) as y_axis, \r\nunnest(ARRAY[SUM(available_rent_general_bikes), SUM(available_return_bikes)]) as data\r\nfrom tran_ubike_realtime)d\r\ngroup by x_axis,y_axis	\N	metrotaipei
youbike_availability	\N	{70}	\N	current	\N	10	minute	交通局	顯示當前臺北市共享單車YouBike的使用情況。	顯示臺北市當前共享單車 YouBike 的使用情況，格式為可借車輛數／全市車位數。資料來源為臺北市政府交通局公開資料，每5分鐘更新一次，反映即時的使用狀況與車輛調度情形，可作為交通監測與市民使用參考依據。	藉由臺北市 YouBike 使用情況的顯示，以及全市可借車輛數約為車柱總數的一半，可大致掌握目前停放於站點與正在使用中的車輛數量。使用者可透過地圖模式查詢臺北市各站點的即時資訊，包括可借車輛數、可還空位數及站點位置，方便即時掌握使用狀況，提升共享單車的使用效率與便利性。	{https://tdx.transportdata.tw/api-service/swagger/basic/2cc9b888-a592-496f-99de-9ab35b7fb70d#/Bike/BikeApi_Availability_2181}	{doit}	2023-12-20 05:56:00+00	2024-03-19 06:08:17.99+00	percent	select '在站車輛' as x_axis, \r\nunnest(ARRAY['可借車輛', '空位']) as y_axis, \r\nunnest(ARRAY[SUM(available_rent_general_bikes), SUM(available_return_bikes)]) as data\r\nfrom tran_ubike_realtime	\N	taipei
food_processing_pass_rate	{"range":["max"],"color":["#4CB495","#F5C860","#ED6A45","#1E88E5","#8E63C7"],"unit":"%"}	{}	{}	static	\N	1	year	衛生福利部食品藥物管理署	顯示臺北市加工食品不合格率歷年趨勢（105-114年）。	此組件彙整衛生福利部食品衛生管理工作資料，篩選肉品、蛋品、水產、蔬果及食品添加物五大類，計算各年度不合格率並以折線圖呈現趨勢。	可用於觀察臺北市加工食品安全品質的長期變化趨勢，輔助食安政策評估與稽查資源配置。	{https://www.mohw.gov.tw/dl-38807-41ca6849-eccd-418a-95f5-20649b0c5bf9.html}	{doit}	2026-05-02 00:00:00+00	2026-05-02 00:00:00+00	time	SELECT MAKE_DATE(year + 1911, 1, 1)::timestamp AS x_axis, category AS y_axis, ROUND((non_compliant_count::float / NULLIF(inspection_count, 0) * 100))::numeric AS data FROM public.food_processing_pass_rate WHERE county = '臺北市' ORDER BY year, category	SELECT MAKE_DATE(year + 1911, 1, 1)::timestamp AS x_axis, category AS y_axis, ROUND((non_compliant_count::float / NULLIF(inspection_count, 0) * 100))::numeric AS data FROM public.food_processing_pass_rate WHERE county = '臺北市' ORDER BY year, category	taipei
food_processing_pass_rate	{"range":["max"],"color":["#4CB495","#F5C860","#ED6A45","#1E88E5","#8E63C7"],"unit":"%"}	{}	{}	static	\N	1	year	衛生福利部食品藥物管理署	顯示雙北加工食品不合格率歷年趨勢（105-114年）。	此組件彙整衛生福利部食品衛生管理工作資料，篩選肉品、蛋品、水產、蔬果及食品添加物五大類，計算雙北各年度不合格率並以折線圖呈現趨勢。	可用於觀察雙北加工食品安全品質的長期變化趨勢，輔助跨區食安政策評估與稽查資源配置。	{https://www.mohw.gov.tw/dl-38807-41ca6849-eccd-418a-95f5-20649b0c5bf9.html}	{doit}	2026-05-02 00:00:00+00	2026-05-02 00:00:00+00	time	SELECT MAKE_DATE(year + 1911, 1, 1)::timestamp AS x_axis, category AS y_axis, ROUND((SUM(non_compliant_count)::float / NULLIF(SUM(inspection_count), 0) * 100))::numeric AS data FROM public.food_processing_pass_rate WHERE county IN ('臺北市', '新北市') GROUP BY year, category ORDER BY year, category	SELECT MAKE_DATE(year + 1911, 1, 1)::timestamp AS x_axis, category AS y_axis, ROUND((SUM(non_compliant_count)::float / NULLIF(SUM(inspection_count), 0) * 100))::numeric AS data FROM public.food_processing_pass_rate WHERE county IN ('臺北市', '新北市') GROUP BY year, category ORDER BY year, category	metrotaipei
\.


COPY public.dashboard_groups (dashboard_id, group_id) FROM stdin;
106	2
401	2
356	2
355	3
359	3
402	3
358	3
\.

--
-- TOC entry 3377 (class 0 OID 0)
-- Dependencies: 222
-- Name: dashboards_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.dashboards_id_seq', (SELECT COALESCE(MAX(id), 0) FROM public.dashboards), true);


--
-- TOC entry 3378 (class 0 OID 0)
-- Dependencies: 224
-- Name: groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.groups_id_seq', (SELECT COALESCE(MAX(id), 4) FROM public.groups), true);


-- Completed on 2024-02-16 10:38:44 UTC

--
-- PostgreSQL database dump complete

SET search_path = public;

\ir add-post-help-agency-manager.sql
\ir add-food-audit-violation-manager.sql
\ir add-health-audit-violation-manager.sql
\ir food-safety-infectious-disease-component.sql
\ir add-food-allergen-classification.sql
\ir agri-noncompliance-manager.sql
